"""Initialization correct migration

Revision ID: d7a58aac86c3
Revises: 
Create Date: 2026-01-21 15:33:20.992746+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a58aac86c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('current_value', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index('ix_goals_main_filter', 'goals', ['user_id', 'is_archived', 'status', 'priority'], unique=False)
    op.create_index('ix_goals_status_finish_date', 'goals', ['status', 'finish_date'], unique=False)
    op.create_index('ix_goals_tags', 'goals', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_created_at_status', 'outbox_events', ['created_at', 'status'], unique=False)
    op.create_index('ix_outbox_processing', 'outbox_events', ['status', 'next_retry_at'], unique=False)
    op.create_table('processed_goal_transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )
    op.create_index(op.f('ix_processed_goal_transactions_goal_id'), 'processed_goal_transactions', ['goal_id'], unique=False)
    op.create_table('goal_notifications',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('last_checked_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_notifications')
    op.drop_index(op.f('ix_processed_goal_transactions_goal_id'), table_name='processed_goal_transactions')
    op.drop_table('processed_goal_transactions')
    op.drop_index('ix_outbox_processing', table_name='outbox_events')
    op.drop_index('ix_outbox_created_at_status', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_index('ix_goals_tags', table_name='goals', postgresql_using='gin')
    op.drop_index('ix_goals_status_finish_date', table_name='goals')
    op.drop_index('ix_goals_main_filter', table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
