"""add_outbox_table

Revision ID: 5b429625f237
Revises: 3cf35170843f
Create Date: 2026-01-09 14:33:35.606775+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b429625f237'
down_revision: Union[str, None] = '3cf35170843f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_created_at', 'outbox_events', ['created_at'], unique=False)
    op.create_index("ix_outbox_pending_retry", "outbox_events", ["status", "next_retry_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_outbox_pending_retry", table_name="outbox_events")
    op.drop_index('ix_outbox_created_at', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
